function createENfigure(Y1, Y2, Y3, Y4)
%CREATEENFIGURE(th, tx, ty, mi)
% Create a set of figures with labels in English.
% Arguments:
%  th:  vector of theta data
%  tx:  vector of x data
%  ty:  vector of y data
%  mi:  vector of MI data

%  Auto-generated by MATLAB on 05-Jan-2016 15:23:58

% Create figure
figure1 = figure('Name','Patient 1: Parameters accepted');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(Y1,'Parent',subplot1,'LineWidth',2);

% Create title
title('Angle of Rotation','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('Iterations','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('Angle','FontWeight','bold','FontSize',14);

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(Y2,'Parent',subplot2,'LineWidth',2);

% Create title
title('Translation in X axis','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('Iterations','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('Position','FontWeight','bold','FontSize',14);

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'all');

% Create plot
plot(Y3,'Parent',subplot3,'LineWidth',2);

% Create title
title('Translation in Y axis','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('Iterations','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('Position','FontWeight','bold','FontSize',14);

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
box(subplot4,'on');
hold(subplot4,'all');

% Create plot
plot(Y4,'Parent',subplot4,'LineWidth',2);

% Create title
title('Mutual Information','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('Iterations','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('MI');

