function createESfigure(th, tx, ty, mi)
%CREATEESFIGURE(th, tx, ty, mi)
% Create a set of figures with labels in Spanish.
% Arguments:
%  th:  vector of theta data
%  tx:  vector of x data
%  ty:  vector of y data
%  mi:  vector of MI data

%  Auto-generated by MATLAB on 16-Dec-2015 10:22:47

% Create figure
figure1 = figure('Name','Patient 1: All parameters');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1,'YGrid','on','XGrid','on');
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(th,'Parent',subplot1,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('Ángulo de rotación','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('iteraciones','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('Ángulo','FontWeight','bold','FontSize',16);

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1,'YGrid','on','XGrid','on');
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(tx,'Parent',subplot2,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('Traslación en X','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('iteraciones','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('Posición','FontWeight','bold','FontSize',16);

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1,'YGrid','on','XGrid','on');
box(subplot3,'on');
hold(subplot3,'all');

% Create plot
plot(ty,'Parent',subplot3,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('Traslación en Y','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('iteraciones','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('Posición','FontWeight','bold','FontSize',16);

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1,'YGrid','on','XGrid','on');
box(subplot4,'on');
hold(subplot4,'all');

% Create plot
plot(mi,'Parent',subplot4,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('Información mutua','FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('iteraciones','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('MI','FontWeight','bold','FontSize',16);

